# Generated by Django 4.2.11 on 2026-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="private/invoices/%Y/%m/"
            ),
        ),
    ]
