# Generated by Django 4.2.11 on 2026-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorkycdocument",
            name="document",
            field=models.FileField(upload_to="private/vendor_documents/"),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="public/vendor_logos/"
            ),
        ),
    ]
